version: "3.9"

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://cbo2002.analiseops.com.br
    ports:
      - "4173:4173"
    restart: unless-stopped
